### ISSUE TITLE
Test function logic

### ISSUE THREAD

**Issue by leshkinski** [rsWinAutomationSupport/rsCertificateStore#3]
Test-TargetResource validates presence of certificate based on the certificate Subject/Common Name which is provided as part of a node's DSC configuration. This config parameter may be static and not necessarily match the certificate's actual value if it is a generated value or a cert that was renewed with the same name, but different expiration date, which would make the cert invalid while still allowing test to return $true.

Suggestion is to validate for certificate presence by comparing thumbprint of the source .cer or .pfx file vs the installed list of certificates.

Test function code in question:
https://github.com/rsWinAutomationSupport/rsCertificateStore/blob/master/DSCResources/RS_rsCertificateStore/RS_rsCertificateStore.psm1#L123-L153

Set function will likely also need a review too:
https://github.com/rsWinAutomationSupport/rsCertificateStore/blob/master/DSCResources/RS_rsCertificateStore/RS_rsCertificateStore.psm1#L81-L83

**Comment by RSabounds** [comment]
See Pull 5. I submitted a code-fix for this issue. Now tests via thumbprint. Code is written if we wish to disable path as a required variable and allow Name to be used as Thumbprint to avoid conflict in a replacement scenario. otherwise, just adjust the name as '$(name)-old'

**Comment by leshkinski** [comment]
Closed by Pull #5
